source 'https://cdn.cocoapods.org'

platform :ios, '16.0'

def shared_pods
  pod 'crossPlatform', :path => '../crossPlatform'
  pod 'Firebase/Analytics'
  pod 'GoogleSignIn'
  pod 'GoogleAPIClientForREST/Drive'
end

target 'hskwidget' do
  use_frameworks! :linkage => :static
  shared_pods
end

target 'HskFlashcardsWidgetExtension' do
  use_frameworks! :linkage => :static
  shared_pods
end

post_install do |installer|
  # Automatically link Version.xcconfig to all Pods targets
  puts "Updating Pods xcconfigs to include Version.xcconfig..."
  installer.aggregate_targets.each do |target|
    target.user_build_configurations.each do |config_name, config|
      path = target.xcconfig_path(config_name)
      if File.exist?(path)
        content = File.read(path)
        unless content.include?('Version.xcconfig')
          File.open(path, 'a') { |f| f.puts "\n#include \"../../../Version.xcconfig\"" }
          puts "  Updated #{path}"
        end
      end
    end
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'

      # Fix for SwiftUICore linking issue in Xcode 16+
      if config.build_settings['OTHER_LDFLAGS'].nil?
        config.build_settings['OTHER_LDFLAGS'] = ['$(inherited)', '-framework "SwiftUI"']
      else
        unless config.build_settings['OTHER_LDFLAGS'].include?('-framework "SwiftUI"')
          config.build_settings['OTHER_LDFLAGS'] << ' -framework "SwiftUI"'
        end
      end
    end
  end
end
