source 'https://cdn.cocoapods.org'

platform :ios, '16.0'

target 'hskwidget' do
  use_frameworks!
  pod 'crossPlatform', :path => '../crossPlatform'  # Local KMP
  pod 'GoogleSignIn'
  pod 'GoogleAPIClientForREST/Drive'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
